### ISSUE TITLE
Configuración de entorno de desarrollo PHP7, MySQL 5 y Laravel 5.4

### ISSUE THREAD

**Issue by joseluisq** [sencico-devs/sesiones-2017#1]
### ¿Cuál es el tema a tratar en el webinar?

Configuración de entorno de desarrollo para proyectos Laravel 5.4

### ¿Puedes describir los puntos a tratar?

Se tratarán los siguientes puntos:

- Introducción a [PHP 7](https://secure.php.net/manual/es/)
  - Principales carácteristicas.
  - Benchmark sobre performance.
- Introducción a [Composer](https://getcomposer.org/)
  - ¿Porqué Composer?
  - Ventajas y desventajas.
  - Principales carácteristicas.
  - Instalación y configuración
- Introducción a [Laravel 5.4](https://laravel.com/docs/5.4/)
  - ¿Porqué Laravel?
  - Ventajas y desventajas.
  - Principales carácteristicas.
  - Instalación
  - Configuración y ejecución de un proyecto.
  - [Laravel Mix](https://github.com/JeffreyWay/laravel-mix) y [VueJS 2](https://vuejs.org/) .

### ¿Quiénes son los expositores?

- [José Luis Quintana](https://github.com/joseluisq)

### ¿En qué horario se realizará?

Propongo el siguiente horario:

- Sábado 25/03/2017 09:30 a.m. (-0500 UTC)

### ¿Quiénes serán los integrantes?

- [x] @joseluisq
- [x] @juanlopezdev

**Comment by luisca-dev** [comment]
-1

**Comment by luisca-dev** [comment]
+1 para React-native

**Comment by joseluisq** [comment]
Claro, `react-native` sería genial. Abre un issue y proponlo. +1

**Comment by juanlopezdev** [comment]
+1 En todos los entornos?

**Comment by joseluisq** [comment]
@winuxue para ver `react-native` tenemos primero que aprender `react`

**Comment by joseluisq** [comment]
@juanlopezdev claro Linux, Win y Mac

**Comment by joseluisq** [comment]
@sencico-devs/developers ¿entonces sábado o domingo el webinar?

**Comment by juanlopezdev** [comment]
Sábado en la mañana

**Comment by joseluisq** [comment]
@juanlopezdev :+1:

**Comment by joseluisq** [comment]
¿A las 09.30 a.m hora de Perú?

**Comment by joseluisq** [comment]
Prerequisitos: 
- MariaDB or MySQL 5+ instalado
- PHP 7.0+ instalado
- `composer` instalado
- `composer global require "laravel/installer"`

**Comment by joseluisq** [comment]
@sencico-devs/developers he agregado el detalle de los contenidos del webinar #2
¿Quién se apunta?

**Comment by juanlopezdev** [comment]
Yo, pero tengo el Homestead instalado.

**Comment by joseluisq** [comment]
@juanlopezdev pero cheka que version de php tienes.
Te he agregado a la lista.

**Comment by joseluisq** [comment]
@juanlopezdev https://github.com/sencico-devs/sesiones-2017/blob/master/sesiones/01.md#prerequisitos

**Comment by joseluisq** [comment]
@sencico-devs/developers propongan algún tema para el siguiente webinar.

@juanlopezdev que tal te fue con el Vagrant?
